services:
  - type: web
    name: medguardian-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
